# Generated by Django 4.0.6 on 2022-07-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=7, verbose_name="Цвет в HEX"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
    ]
