# Generated by Django 4.0.6 on 2022-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_tag_color_alter_tag_name_alter_tag_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=7, verbose_name="Цвет в HEX"),
                ),
            ],
            options={
                "unique_together": {("name", "measurement_unit")},
            },
        ),
    ]
