# Generated by Django 4.0.6 on 2022-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_ingredientamount_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientamount",
            name="amount",
            field=models.IntegerField(verbose_name="Количество"),
        ),
    ]
