# Generated by Django 4.0.6 on 2022-08-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                to="recipes.ingredientamount",
                verbose_name="Список ингредиентов",
            ),
        ),
    ]
