# Generated by Django 4.0.6 on 2022-08-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0018_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("-id",),
                "verbose_name": "Избранный рецепт",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-id",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ("-id",),
                "verbose_name": "Корзина",
                "verbose_name_plural": "В корзине",
            },
        ),
    ]
