# Generated by Django 4.0.6 on 2022-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0020_alter_tag_unique_together_tag_unique_tag_name_color",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ingredient",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"),
                name="unique_ingredient_name_measurement_unit",
            ),
        ),
    ]
