# Generated by Django 4.0.6 on 2022-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_alter_ingredient_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_user_favorite_recipe",
        ),
        migrations.RemoveConstraint(
            model_name="shoppingcart",
            name="unique_user_recipe_in_shoppingcart",
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_favorite_user_recipe"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"),
                name="unique_shoppingcart_user_recipe",
            ),
        ),
    ]
