# Generated by Django 4.0.6 on 2022-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0022_remove_favorite_unique_user_favorite_recipe_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientamount",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
    ]
