# Generated by Django 4.0.6 on 2022-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_subscription_author_alter_subscription_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "author"),
                name="unique_user_author_subscription",
            ),
        ),
    ]
