# Generated by Django 4.0.6 on 2022-08-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscription_unique_user_author_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-id"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
    ]
