# Generated by Django 4.0.6 on 2022-08-10 08:09

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user", django.db.models.expressions.F("author")),
                    _negated=True,
                ),
                name="prevent_self_subscription",
            ),
        ),
    ]
