# Generated by Django 4.0.6 on 2022-08-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_subscription_prevent_self_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("-id",),
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
