# Generated by Django 4.0.6 on 2022-08-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_subscription_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_user_author_subscription",
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "author"),
                name="unique_subscription_user_author",
            ),
        ),
    ]
